# Generated by Django 5.1 on 2024-08-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_fake_data'),
        ('blog', '0003_add_fake_data_2'),
    ]

    operations = [
    ]
