# Generated by Django 5.0.6 on 2024-08-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags_alter_post_image'),
        ('blog', '0007_create_fake_data'),
    ]

    operations = [
    ]
